export default [
  ['Region', 'Label', 'Selected'],
  ['US', 'North America', 0],
  ['CA', 'North America', 0],
  ['GL', 'North America', 0],
  ['AR', 'Latin and South America', 0],
  ['BO', 'Latin and South America', 0],
  ['BR', 'Latin and South America', 0],
  ['CL', 'Latin and South America', 0],
  ['CO', 'Latin and South America', 0],
  ['EC', 'Latin and South America', 0],
  ['FK', 'Latin and South America', 0],
  ['GF', 'Latin and South America', 0],
  ['GY', 'Latin and South America', 0],
  ['PY', 'Latin and South America', 0],
  ['PE', 'Latin and South America', 0],
  ['SR', 'Latin and South America', 0],
  ['UY', 'Latin and South America', 0],
  ['VE', 'Latin and South America', 0],
  ['NI', 'Latin and South America', 0],
  ['HN', 'Latin and South America', 0],
  ['SV', 'Latin and South America', 0],
  ['BZ', 'Latin and South America', 0],
  ['MX', 'Latin and South America', 0],
  ['PA', 'Latin and South America', 0],
  ['CU', 'Latin and South America', 0],
  ['HT', 'Latin and South America', 0],
  ['BS', 'Latin and South America', 0],
  ['DO', 'Latin and South America', 0],
  ['CR', 'Latin and South America', 0],
  ['JM', 'Latin and South America', 0],
  ['AX', 'Europe', 0],
  ['AL', 'Europe', 0],
  ['AD', 'Europe', 0],
  ['AT', 'Europe', 0],
  ['BY', 'Europe', 0],
  ['BE', 'Europe', 0],
  ['BA', 'Europe', 0],
  ['BG', 'Europe', 0],
  ['HR', 'Europe', 0],
  ['CZ', 'Europe', 0],
  ['DK', 'Europe', 0],
  ['EE', 'Europe', 0],
  ['FO', 'Europe', 0],
  ['FI', 'Europe', 0],
  ['FR', 'Europe', 0],
  ['DE', 'Europe', 0],
  ['GI', 'Europe', 0],
  ['GR', 'Europe', 0],
  ['GG', 'Europe', 0],
  ['VA', 'Europe', 0],
  ['HU', 'Europe', 0],
  ['IS', 'Europe', 0],
  ['IE', 'Europe', 0],
  ['IM', 'Europe', 0],
  ['IT', 'Europe', 0],
  ['JE', 'Europe', 0],
  ['LV', 'Europe', 0],
  ['LI', 'Europe', 0],
  ['LT', 'Europe', 0],
  ['LU', 'Europe', 0],
  ['MK', 'Europe', 0],
  ['MT', 'Europe', 0],
  ['MD', 'Europe', 0],
  ['MC', 'Europe', 0],
  ['ME', 'Europe', 0],
  ['NL', 'Europe', 0],
  ['NO', 'Europe', 0],
  ['PL', 'Europe', 0],
  ['PT', 'Europe', 0],
  ['RO', 'Europe', 0],
  ['RU', 'Europe', 0],
  ['SM', 'Europe', 0],
  ['RS', 'Europe', 0],
  ['SK', 'Europe', 0],
  ['SI', 'Europe', 0],
  ['ES', 'Europe', 0],
  ['SJ', 'Europe', 0],
  ['SE', 'Europe', 0],
  ['CH', 'Europe', 0],
  ['UA', 'Europe', 0],
  ['GB', 'Europe', 0],
  ['DZ', 'Northern Africa', 0],
  ['EG', 'Northern Africa', 0],
  ['LY', 'Northern Africa', 0],
  ['MA', 'Northern Africa', 0],
  ['TN', 'Northern Africa', 0],
  ['EH', 'Northern Africa', 0],
  ['SD', 'Northern Africa', 0],
  ['AO', 'Central Africa', 0],
  ['CM', 'Central Africa', 0],
  ['CF', 'Central Africa', 0],
  ['TD', 'Central Africa', 0],
  ['CG', 'Central Africa', 0],
  ['CD', 'Central Africa', 0],
  ['GQ', 'Central Africa', 0],
  ['GA', 'Central Africa', 0],
  ['ST', 'Central Africa', 0],
  ['BJ', 'Central Africa', 0],
  ['BF', 'Central Africa', 0],
  ['CV', 'Central Africa', 0],
  ['CI', 'Central Africa', 0],
  ['GM', 'Central Africa', 0],
  ['GH', 'Central Africa', 0],
  ['GN', 'Central Africa', 0],
  ['GW', 'Central Africa', 0],
  ['LR', 'Central Africa', 0],
  ['ML', 'Central Africa', 0],
  ['MR', 'Central Africa', 0],
  ['NE', 'Central Africa', 0],
  ['NG', 'Central Africa', 0],
  ['SH', 'Central Africa', 0],
  ['SN', 'Central Africa', 0],
  ['SL', 'Central Africa', 0],
  ['TG', 'Central Africa', 0],
  ['BI', 'Central Africa', 0],
  ['KM', 'Central Africa', 0],
  ['DJ', 'Central Africa', 0],
  ['ER', 'Central Africa', 0],
  ['ET', 'Central Africa', 0],
  ['KE', 'Central Africa', 0],
  ['MG', 'Central Africa', 0],
  ['MW', 'Central Africa', 0],
  ['MU', 'Central Africa', 0],
  ['YT', 'Central Africa', 0],
  ['MZ', 'Central Africa', 0],
  ['RE', 'Central Africa', 0],
  ['RW', 'Central Africa', 0],
  ['SC', 'Central Africa', 0],
  ['SO', 'Central Africa', 0],
  ['SS', 'Central Africa', 0],
  ['TZ', 'Central Africa', 0],
  ['UG', 'Central Africa', 0],
  ['ZM', 'Central Africa', 0],
  ['ZW', 'Central Africa', 0],
  ['BW', 'Southern Africa', 0],
  ['LS', 'Southern Africa', 0],
  ['NA', 'Southern Africa', 0],
  ['ZA', 'Southern Africa', 0],
  ['SZ', 'Southern Africa', 0],
  ['AU', 'Australia and Oceania', 0],
  ['NZ', 'Australia and Oceania', 0],
  ['NF', 'Australia and Oceania', 0],
  ['AS', 'Australia and Oceania', 0],
  ['AU', 'Australia and Oceania', 0],
  ['CK', 'Australia and Oceania', 0],
  ['FJ', 'Australia and Oceania', 0],
  ['PF', 'Australia and Oceania', 0],
  ['GU', 'Australia and Oceania', 0],
  ['KI', 'Australia and Oceania', 0],
  ['MH', 'Australia and Oceania', 0],
  ['FM', 'Australia and Oceania', 0],
  ['NR', 'Australia and Oceania', 0],
  ['NC', 'Australia and Oceania', 0],
  ['NZ', 'Australia and Oceania', 0],
  ['NU', 'Australia and Oceania', 0],
  ['NF', 'Australia and Oceania', 0],
  ['MP', 'Australia and Oceania', 0],
  ['PW', 'Australia and Oceania', 0],
  ['PG', 'Australia and Oceania', 0],
  ['PN', 'Australia and Oceania', 0],
  ['WS', 'Australia and Oceania', 0],
  ['SB', 'Australia and Oceania', 0],
  ['TK', 'Australia and Oceania', 0],
  ['TO', 'Australia and Oceania', 0],
  ['TV', 'Australia and Oceania', 0],
  ['VU', 'Australia and Oceania', 0],
  ['WF', 'Australia and Oceania', 0],
  ['RU', 'Russia, Kazakhstan and Mongolia', 0],
  ['KZ', 'Russia, Kazakhstan and Mongolia', 0],
  ['MN', 'Russia, Kazakhstan and Mongolia', 0],
  ['SU', 'Russia, Kazakhstan and Mongolia', 0],
  ['SA', 'Middle East', 0],
  ['AM', 'Middle East', 0],
  ['AZ', 'Middle East', 0],
  ['BH', 'Middle East', 0],
  ['GE', 'Middle East', 0],
  ['IR', 'Middle East', 0],
  ['IQ', 'Middle East', 0],
  ['IL', 'Middle East', 0],
  ['JO', 'Middle East', 0],
  ['KW', 'Middle East', 0],
  ['LB', 'Middle East', 0],
  ['NT', 'Middle East', 0],
  ['OM', 'Middle East', 0],
  ['QA', 'Middle East', 0],
  ['SY', 'Middle East', 0],
  ['TR', 'Middle East', 0],
  ['TM', 'Middle East', 0],
  ['AE', 'Middle East', 0],
  ['YE', 'Middle East', 0],
  ['IO', 'India, China and Southeastern Asia', 0],
  ['IN', 'India, China and Southeastern Asia', 0],
  ['CN', 'India, China and Southeastern Asia', 0],
  ['TW', 'India, China and Southeastern Asia', 0],
  ['BN', 'India, China and Southeastern Asia', 0],
  ['KH', 'India, China and Southeastern Asia', 0],
  ['ID', 'India, China and Southeastern Asia', 0],
  ['LA', 'India, China and Southeastern Asia', 0],
  ['MY', 'India, China and Southeastern Asia', 0],
  ['MM', 'India, China and Southeastern Asia', 0],
  ['PH', 'India, China and Southeastern Asia', 0],
  ['SG', 'India, China and Southeastern Asia', 0],
  ['TH', 'India, China and Southeastern Asia', 0],
  ['TL', 'India, China and Southeastern Asia', 0],
  ['VN', 'India, China and Southeastern Asia', 0],
  ['AF', 'India, China and Southeastern Asia', 0],
  ['BD', 'India, China and Southeastern Asia', 0],
  ['BT', 'India, China and Southeastern Asia', 0],
  ['IO', 'India, China and Southeastern Asia', 0],
  ['BN', 'India, China and Southeastern Asia', 0],
  ['KH', 'India, China and Southeastern Asia', 0],
  ['TP', 'India, China and Southeastern Asia', 0],
  ['HK', 'India, China and Southeastern Asia', 0],
  ['ID', 'India, China and Southeastern Asia', 0],
  ['JP', 'India, China and Southeastern Asia', 0],
  ['KP', 'India, China and Southeastern Asia', 0],
  ['KR', 'India, China and Southeastern Asia', 0],
  ['KG', 'India, China and Southeastern Asia', 0],
  ['LA', 'India, China and Southeastern Asia', 0],
  ['MO', 'India, China and Southeastern Asia', 0],
  ['MY', 'India, China and Southeastern Asia', 0],
  ['MV', 'India, China and Southeastern Asia', 0],
  ['MN', 'India, China and Southeastern Asia', 0],
  ['MM', 'India, China and Southeastern Asia', 0],
  ['NR', 'India, China and Southeastern Asia', 0],
  ['NP', 'India, China and Southeastern Asia', 0],
  ['MP', 'India, China and Southeastern Asia', 0],
  ['PK', 'India, China and Southeastern Asia', 0],
  ['PW', 'India, China and Southeastern Asia', 0],
  ['LK', 'India, China and Southeastern Asia', 0],
  ['TJ', 'India, China and Southeastern Asia', 0],
  ['UZ', 'India, China and Southeastern Asia', 0]
];
